### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by emilljungberg** [spinicist/riesling#2]
Build instructions have changed.

**Comment by emilljungberg** [comment]
Specify which versions of `clang`/`gcc`/`cmake` this works with and which are minimum levels.

**Comment by emilljungberg** [comment]
Add in `curl` as requirement. Although commonly installed it isn't by default in ubuntu and throws a cryptic error message if it isn't installed.

**Comment by spinicist** [comment]
README has been improved when adding the documentation https://github.com/spinicist/riesling/commit/63116d9b0436c5ecf1c370cd0de381ca6941be3c
