### ISSUE TITLE
Purpose of read_gap

### ISSUE THREAD

**Issue by MartinK84** [spinicist/riesling#22]
I'm currently in the process of trying to reconstruct my own 3D-UTE data with riesling. Creating the relevant k-space and trajectory shapes is okay in my opinion and well enough documented (after finding the tutorial notebook in the other repository). However, I'm struggling a bit with the info header because not all parameters are documented (looking here: https://riesling.readthedocs.io/en/latest/docs/data.html).

Especially the `read_gap` parameter is a bit puzzling to me. I would assume that this is the number of additional data points that should be discarded at the beginning of each readout/ADC. But I'm not sure and would need some clarification and would also suggest updating this info in the documentation. 

I think most of the other info parameters are pretty self-explanatory, however, it would still be great if more details could be added to the documentation. Like the unit of TR, etc.

**Comment by MartinK84** [comment]
I'm also currently not fully sure about the `spokes_hi` parameter, is this supposed to be the number of acquired spokes or the Nyquist number of spokes for a fully sampled k-space that corresponds to the given matrix size? I'm asking because for the Phantom dataset from the tutorial notebook the number of spokes in k-space is 24575 but the info.spokes_hi is 21845, so the numbers do not match :astonished:

**Comment by spinicist** [comment]
> Especially the `read_gap` parameter is a bit puzzling to me. I would assume that this is the number of additional data points that should be discarded at the beginning of each readout/ADC. But I'm not sure and would need some clarification and would also suggest updating this info in the documentation.

`read_gap` is indeed the number of points that fall into the ZTE dead-time gap and should be discarded. I will update the documentation, apologies that this was missed.

> I think most of the other info parameters are pretty self-explanatory, however, it would still be great if more details could be added to the documentation. Like the unit of TR, etc.

Yes, this will also be added. Technically the units of TR and the image dimensions are only used when constructing a NIFTI header, and hence should be seconds and millimeters respectively.

**Comment by spinicist** [comment]
> I'm also currently not fully sure about the `spokes_hi` parameter, is this supposed to be the number of acquired spokes or the Nyquist number of spokes for a fully sampled k-space that corresponds to the given matrix size? I'm asking because for the Phantom dataset from the tutorial notebook the number of spokes in k-space is 24575 but the info.spokes_hi is 21845, so the numbers do not match 😲

The use of `spokes_hi` and `spokes_lo` is one place where riesling is tailored towards ZTE acquisitions, specifically those with a WASPI-type acquisition with a second low-resolution k-space to fill the dead-time gap.

From the documentation: "`spokes_hi` sets the number of spokes in the main, high-resolution k-space acquisition." For UTE data this should be the number of spokes in the acquisition, and `spokes_lo` should be zero.

The tutorial includes the use of a low-resolution k-space, hence the discrepancy between `spokes_hi` and the total number of spokes. The total number should be equal to `spokes_hi` + `spokes_lo`.

I am open to suggestions as to renaming these header fields for clarity.

**Comment by MartinK84** [comment]
I got confused because I was thinking if `spokes_lo` could mean something like fully sampled center-region of k-space for some kind of k-zero based calibration.  With what you wrote I think the names `spokes_hi`+ `spokes_lo` are fine and make sense, it should just be clarified in the documentation that both are tailored for ZTE acquisitions. Maybe just explicitly state this and also state how they are supposed to be set for 3D-UTE.

**Comment by spinicist** [comment]
I have updated the documentation, I hope it is clearer now.

**Comment by MartinK84** [comment]
Jepp, thanks! -> issue closed
