### ISSUE TITLE
Debian 10 linking fails.

### ISSUE THREAD

**Issue by uecker** [spinicist/riesling#27]
Hi Toby,
on my Debian buster notebook linking fails (after two hours compiling or so). Any ideas? 

[100%] Linking CXX executable riesling
/usr/bin/ld: CMakeFiles/riesling.dir/src/main_phantom.cpp.o: in function `main_phantom(args::Subparser&)':
main_phantom.cpp:(.text+0x35da): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: main_phantom.cpp:(.text+0x3619): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: main_phantom.cpp:(.text+0x3628): undefined reference to `std::filesystem::__cxx11::path::replace_extension(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: libvineyard.a(fft_util.cpp.o): in function `FFT::WisdomPath[abi:cxx11]()':
fft_util.cpp:(.text+0xd2e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: fft_util.cpp:(.text+0xda5): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: fft_util.cpp:(.text+0xeb0): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/bin/ld: fft_util.cpp:(.text+0xffc): undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
/usr/bin/ld: fft_util.cpp:(.text+0x106b): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: fft_util.cpp:(.text+0x1161): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: libvineyard.a(io_hd5.cpp.o): in function `HD5::Reader::Reader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Log&)':
io_hd5.cpp:(.text+0xd9a): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: io_hd5.cpp:(.text+0xda2): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: libvineyard.a(parse_args.cpp.o): in function `OutName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
parse_args.cpp:(.text+0x36a): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: parse_args.cpp:(.text+0x42b): undefined reference to `std::filesystem::__cxx11::path::replace_extension(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/riesling.dir/build.make:345: riesling] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/riesling.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2

**Comment by spinicist** [comment]
Hello,

First a tangent - you correctly highlight that building the dependencies takes a long time. Most of that is spent compiling ITK and its dependencies, only to enable writing out nifti files. I have pushed a commit on main to remove ITK and use the nifti C library directly. I hope this should cut the first compile time by about half (FFTW is the other major time sink).

Your actual problem appears to be a quirk of GCC 8 (which I think is the Debian 10 system compiler?) which requires an extra flag to link the C++ filesystem library correctly. There is a note at the bottom of the page here https://en.cppreference.com/w/cpp/filesystem about this that I previously did not know about.

I have pushed a commit on a new branch `stdfs` (https://github.com/spinicist/riesling/tree/stdfs) which I hope has a work-around in `CMakeLists.txt`. Could you please try this branch and see what happens?

**Comment by uecker** [comment]
Am Montag, den 06.09.2021, 17:21 +0000 schrieb Tobias Wood:
> Hello,
> 
> First a tangent - you correctly highlight that building the dependencies takes a long time. Most
> of that is spent compiling ITK and its dependencies, only to enable writing out nifti files. I
> have pushed a commit on main to remove ITK and use the nifti C library directly. I hope this
> should cut the first compile time by about half (FFTW is the other major time sink).
> 
> Your actual problem appears to be a quirk of GCC 8 (which I think is the Debian 10 system
> compiler?) which requires an extra flag to link the C++ filesystem library correctly. There is a
> note at the bottom of the page here https://en.cppreference.com/w/cpp/filesystem about this that I
> previously did not know about.
> 
> I have pushed a commit on a new branch `stdfs` (https://github.com/spinicist/riesling/tree/stdfs)
> which I hope has a work-around in `CMakeLists.txt`. Could you please try this branch and see what
> happens?

I installed libnifti-dev, but now run into:


CMake Error at cmake/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package):
  By not providing "Findnifti.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "nifti", but
  CMake did not find one.

  Could not find a package configuration file provided by "nifti" with any of
  the following names:

    niftiConfig.cmake
    nifti-config.cmake

  Add the installation prefix of "nifti" to CMAKE_PREFIX_PATH or set
  "nifti_DIR" to a directory containing one of the above files.  If "nifti"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!


Best,
Martin

**Comment by spinicist** [comment]
Sadly I typed `nifti` instead of `NIFTI` as the package name in CMakeLists.txt, but because APFS is case-insensitive on my Mac CMake managed to find it anyway. But Linux is (correctly) case-sensitive, hence the failure which was picked up in the CI but I hadn't waited for that to finish.

This has now been fixed, please try the `stdfs` branch again. It built successfully in the Linux CI so fingers crossed.

(You should not need to install any libraries - vcpkg will build them from source)

**Comment by uecker** [comment]
The nifit problem is solved but not yet the original problem. (The pre-compiled binary works fine.)

**Comment by spinicist** [comment]
Okay. I will have to try and find a Linux system I can install the same version of GCC on and debug further.

Please can you confirm the exact version of GCC on your system?

**Comment by uecker** [comment]
The default system compiler is: gcc (Debian 8.3.0-6) 8.3.0

Unfortunately,  I never understood how cmake works, so I can not really help with this, but if you need other information let me know.

**Comment by spinicist** [comment]
I asked for some help on the CMake Discourse and have made another attempt at fixing this on the `stdfs` branch. Sadly Github Actions does not have GCC 8 easily available to test against (only 7, 9 & 10, I have no idea why 8 is missing) so I can't properly test this - I have tested against GCC 9 and that still compiles fine.
