### ISSUE TITLE
trajectory scaling

### ISSUE THREAD

**Issue by uecker** [spinicist/riesling#29]
Scaling the trajectory to have a maximum k-space of 1 in each direction seems a bit strange to me. I think -0.5 to 0.5 is more common and seems to make more sense.

Although the justification for normalization seems not entirely convincing:  "This is in contrast to toolboxes such as BART where inverse wave-number is often used. The decision to drop this convention was taken because RIESLING allows the user to change the reconstruction oversampling factor, and hence the k-space locations must undergo a rescaling internally anyway."  Especially for brain imaging, I do not understand why users would have to change the oversampling factor retrospectively. The FOV is easily selected correctly during acquisition (this is more difficult for cardiac imaging). So assuming that the FOV was correct, a trajectory in units of 1 / FOV then automatically encodes the information about the matrix size, while this information is lost during normalization and then requires additional steps by the user get a correct reconstruction.

Maybe this decision could be better explained?

**Comment by spinicist** [comment]
We have changed the scaling to be between -0.5 and 0.5 as we agree this is more common. That sentence has been removed from the documentation.

The configurable oversampling factor is provided for several reasons. Primarily,  Beatty et al (http://ieeexplore.ieee.org/document/1435541/) showed that an oversampling ratio of only 1.3 could produce acceptable image quality, and hence we wish to leave it up to the user to choose what oversampling they think provides the best reconstruction for them. Although our own primary application is neuro, we do not wish to limit possible applications, and 
there are several neuro applications where the user may wish to change the FOV retrospectively, e.g. small field-of-view imaging or spine.

However, a requirement for ZTE is supporting WASPI (http://doi.wiley.com/10.1002/mrm.21174) type acquisitions where we must combine multiple k-spaces acquired with different trajectories. We have one specific workflow where these k-spaces are stored separately, and here it is very useful to have the matrix size stored explicitly, as the maximum value in the trajectory is no longer related to the desired reconstruction size.
