### ISSUE TITLE
Image resolution `nii` command

### ISSUE THREAD

**Issue by emilljungberg** [spinicist/riesling#40]
When I convert an image file to nifti using the `nii` command the resolution comes out to 1x1x1, despite the resolution in the header being different. I have a file reconstructed using rss where I've added `--keep` to maintain the info structure. The relevant line reads
```
Voxel-size: 2.36842  2.3913 5.88235	 TR: 1	 Origin: 0 0 0
```
When I use `riesling nii` to do the convert I get a nifti file with the following header information
```
dim1		76
dim2		92
dim3		34
dim4		1
datatype	32
pixdim1		1.000000
pixdim2		1.000000
pixdim3		1.000000
pixdim4		0.000000
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+
```

I've looked in the `nii` command source code but cannot figure out why it wouldn't pick up the right info. Any thoughts?

**Comment by spinicist** [comment]
This is now fixed by https://github.com/spinicist/riesling/commit/dbd8d43b770340334acc53dd1f03f6145ecd5ece on the `py` branch.
