### ISSUE TITLE
Examples outdated

### ISSUE THREAD

**Issue by MartinK84** [spinicist/riesling#43]
It appears as if most, it not even all, examples are outdated and non functional anymore. Which I totally understand (who has the time for that...), but is there possibly one working example available that works with the current version? After hours of playing around with the commands and puzzling together left-overs from the old examples I did not manage to get the simplest things to work. 

Initially I tried to put in my own data as I did before, but apparently there have been some changes in data structure and fields and I'm constantly running into errors like ```Tensor noncartesian: Requested rank 5, on-disk rank 4```. So I tried to just play with phantoms in order to figure out the new structure. Creating a phantom worked using:
```
riesling phantom --matrix=96 --channels=8 phantom
```
Since apparently phantoms are now just imaging data I then tried to fft it (since I wanted to figure out the k-space data structure and info struct for k-space data) by running
```
riesling nufft --fwd phantom.h5 --dset=image
```
which then again ended in ```Tensor image: has rank 5, expected 6```.

I'm sorry that I have to ask for such basic help, maybe there is an up-to-date tutorial or description and I simply missed it?

**Comment by spinicist** [comment]
I'm really sorry about this.

Try the updated tutorial in the `zinfandel` branch: https://github.com/spinicist/riesling-examples/blob/zinfandel/tutorial.ipynb

I haven't merged updated examples to the main branch because one of the things I did at the end of last year was finally move the Python plotting code into the main repo, and the examples aren't properly updated to use that yet.

The data format has an extra dimension to start supporting multi-slice / multi-slab trajectories. There is Python code to write the new format here: https://github.com/spinicist/riesling/blob/main/python/riesling/data.py and the Matlab writer should also work: https://github.com/spinicist/riesling/blob/main/matlab/riesling_write.m

**Comment by MartinK84** [comment]
Thanks a lot!
Got the first reconstruction to work, there will be a pull request with some potential fixes in the MATLAB wrapper come in soon :-)

**Comment by fyrdahl** [comment]
> the Matlab writer should also work: https://github.com/spinicist/riesling/blob/main/matlab/riesling_write.m

I'm not really getting along with the MATLAB writer. I was attempting to input my own Cartesan k-space, and then grid it.

**Setup code** (using [phantom3d](https://www.mathworks.com/matlabcentral/fileexchange/9416-3d-shepp-logan-phantom) from the MATLAB File Exchange):
````
clc; clearvars;

setenv('PATH', '/mnt/d1/shared/sw/riesling/build');
addpath('/mnt/d1/shared/sw/riesling/matlab');

nSamples = 256;
nSpokes = 1024;

img = single(phantom3d(nSamples/2)); % [128 128 128]
img = padarray(img, [1 1 1].*nSamples/4); % [256 256 256]
ksp = cfftn(img, [1 2 3]);
ksp = permute(ksp, [4 1 2 3]); % [1 256 256 256]

phi1 = 0.4656; phi2 = 0.6823;
kt = linspace(-0.5, 0.5, nSamples+1); kt(end) = [];
traj = zeros(3, nSamples, nSpokes); % [3 256 1024]
for s = 1:nSpokes
    azi = 2*pi*mod(s*phi2, 1);
    pol = acos(mod(s*phi1, 1));
    traj(1, :, s) = kt' * (cos(azi) .* sin(pol));
    traj(2, :, s) = kt' * (sin(azi) .* sin(pol));
    traj(3, :, s) = kt' *              cos(pol);
end

info = riesling_info();
info.matrix = [nSamples; nSamples; nSamples]./2;
info.channels = 1;
````

**First attempt**
````
delete('ksp.h5'); riesling_write('ksp.h5', ksp, traj, info, 'cartesian')
system('riesling grid ksp.h5 -f') 
````
Resulted in error: ``Tensor cartesian: has rank 4, expected 5``

**Second attempt**
````
ksp = permute(ksp,[5 1 2 3 4]); % [1 1 256 256 256]
delete('ksp.h5'); riesling_write('ksp.h5', ksp, traj, info, 'cartesian');
````
Resulted in error: ``The rank of the dataspace does not match the length of the extent arguments.``

**Third attempt**
For the third attempt, I modified ``riesling_write.m`` by adding a special case for ``cartesian`` by adding the following lines:
````
elseif strcmp(tensorName,'cartesian')
    Ndims = 5;
````

````
ksp = permute(ksp,[5 1 2 3 4]); % [1 1 256 256 256]
delete('ksp.h5'); riesling_write('ksp.h5', ksp, traj, info, 'cartesian');
system('riesling grid ksp.h5 -f -v')
system('riesling nufft ksp-grid.h5 -v')
img_nufft = riesling_read('ksp-grid-nufft.h5');
````
Resulted in error: ``Error: H5G__loc_find_cb    object 'info' doesn't exist``

**Final attempt**
Finally, I modified ``riesling_read.m`` as well by adding the following parts:
````
is_channels_data = any(contains({file_info.Datasets.Name}, 'channels'));

...

if ~is_channels_data
    % always read info (unless channels)
    info = h5read(fname, '/info');
end

...

elseif is_channels_data
    data = h5read(fname, '/channels');
    img = data.r + 1j*data.i;

    varargout{1} = img;
````

After these modifications, the code ran successfully :tada:.

I don't know enough about the underlying datatypes to understand if I basically brute-forced by way through this or if these changes are useful. If any of the above changes to ``riesling_read`` or ``riesling_write`` are useful, I'd be happy to create PR's. Probably needs some review by @spinicist first though...

**Comment by spinicist** [comment]
Clearly the Matlab code needs some love. I'm very happy to review a PR.

I have now updated the data format documentation 😅
