### ISSUE TITLE
Different trajectories for different slabs

### ISSUE THREAD

**Issue by fyrdahl** [spinicist/riesling#47]
I've noticed that `trajectory` can only have 3 dimensions, whereas `noncartesian` also has a `slab` and `volume` dimension. I see in `docs/data.rts` that "The trajectory is assumed to repeat for each slab and volume."

Browsing through old commits, I saw that there used to be a `frame` dimension in `trajectory`, which was quickly removed. Based on the code, I assume the trajectory `frame` represents a different trajectory for each `slab`? Is there a good reason why this was removed? It sounds like a useful feature, so if it was due to a lack of use cases or interest, I vote to reinstate it.

**Comment by spinicist** [comment]
Hello,

This functionality is still present, but in an admittedly non-obvious place. You can use `riesling frames` to generate a `.h5` file which you can then pass to the reconstruction with `--basis=frames.h5`. The different frames will then end up on the inner-most dimension (first from riesling's point of view, last from Python's point of view).

If your trajectory has 512 traces/spokes, split into 4 frames of 128 each, then the call is:
`riesling frames --frames=128,128,128,128 frames128.h5`.

You plot the result with `riesling.plot.basis()`. I don't have functionality for any more complicated orderings than this at present.

**Comment by spinicist** [comment]
PS I know this isn't immediately obvious, but I promise it makes the internal code of `riesling` _much_ cleaner!
